/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_yylyingy_gifencodedecode_GifDecoder */

#ifndef _Included_io_github_yylyingy_gifencodedecode_GifDecoder
#define _Included_io_github_yylyingy_gifencodedecode_GifDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_yylyingy_gifencodedecode_GifDecoder
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_yylyingy_gifencodedecode_GifDecoder_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     io_github_yylyingy_gifencodedecode_GifDecoder
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_yylyingy_gifencodedecode_GifDecoder_nativeClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_github_yylyingy_gifencodedecode_GifDecoder
 * Method:    nativeLoad
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_yylyingy_gifencodedecode_GifDecoder_nativeLoad
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     io_github_yylyingy_gifencodedecode_GifDecoder
 * Method:    nativeGetFrameCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_yylyingy_gifencodedecode_GifDecoder_nativeGetFrameCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_github_yylyingy_gifencodedecode_GifDecoder
 * Method:    nativeGetFrame
 * Signature: (JI)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_io_github_yylyingy_gifencodedecode_GifDecoder_nativeGetFrame
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     io_github_yylyingy_gifencodedecode_GifDecoder
 * Method:    nativeGetDelay
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_io_github_yylyingy_gifencodedecode_GifDecoder_nativeGetDelay
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     io_github_yylyingy_gifencodedecode_GifDecoder
 * Method:    nativeGetWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_yylyingy_gifencodedecode_GifDecoder_nativeGetWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_github_yylyingy_gifencodedecode_GifDecoder
 * Method:    nativeGetHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_yylyingy_gifencodedecode_GifDecoder_nativeGetHeight
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
